### ISSUE TITLE
[BUG] Slow performance opening 'more info' dialogs

### ISSUE THREAD

**Issue by basilfx** [NemesisRE/kiosk-mode#178] opened 2024-01-04 23:54 UTC
**Describe the bug**
Opening 'more info' dialogs (such as the climate dialog) performs slow and sluggish. Once I remove kiosk-mode, performance restores. I also have the feeling that this happened since 2024.1.0.

**To Reproduce**
1. Use lower-end Android hardware.
2. Install kiosk-mode.
3. Add a climate entity to a dashboard.
4. Open it, notice sluggish behavior.

**Expected behavior**
Performance on par as without kiosk mode.

**Screenshots**
I got a movie to demonstrate this issue. You can find it below.

https://github.com/NemesisRE/kiosk-mode/assets/815976/bf80852e-ddf3-4f01-be60-a826df132c5e

In addition, I got this profiler screenshot, which I recorded after opening the 'more info' dialog once, but no interaction happened during the recording:

<img width="2032" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/815976/2aa72e6a-4656-4668-8430-72dbd9b87d0f">

**Versions:**
 - Home Assistant: 2024.1.0
 - Kiosk-Mode 5.1.0

**Additional context**
I use it on a singel dashboard, using the following configuration:

```
kiosk_mode:
  mobile_settings:
    hide_header: true
    ignore_entity_settings: true
```

This is very much noticeable on lower-end hardware. In this case, I run the Android app on a NSPanel Pro (which runs Android 8.1, Webkit 107).

**Comment by elchininet** [comment] 2024-01-05 03:01
Hi @basilfx,
I‘ll update to `2024.1.0` to see if I can reproduce it.
Regards

**Comment by elchininet** [comment] 2024-01-05 03:52
Hi @basilfx,
Could you try to install [the version 5.0.0](https://github.com/NemesisRE/kiosk-mode/releases/tag/v5.0.0) and check if your get the same behaviour?
I have a strong feeling that a feature that was introduced in `5.0.1` is very expensive for your device.

**Comment by basilfx** [comment] 2024-01-05 13:01
I rolled back to 5.0.0 and that made a difference.

**Comment by elchininet** [comment] 2024-01-05 13:18
Hi @basilfx,

Then it is confirmed. In `5.0.1` we introduce a feature that makes the code easier to manage because it search for an element deeper in the DOM tree (so there is not need of creating conditions for, if Home Assistant is in this version do this, if it is in this another version then do that).

That seems to be OK for more modern devices capable of dealing with that deep search, but it is not OK for older devices (the oldest Android device that I have here is a Samsung Galaxy Tab A8). As `kiosk-mode` could be used to bring to life an old device that we have around the house, I think that in this case is more important performance over maintanability and escalability of the code. I‘ll remove the deep query from the more-info dialogs and bring back those version checks.

Letting this issue open until then.

Regards

**Comment by elchininet** [comment] 2024-01-05 15:08
Hi @basilfx,
When [this](https://github.com/NemesisRE/kiosk-mode/pull/179) gets merged and a new version is released, your issue should be solved.
Regards

**Closed** 2024-01-05 19:40 UTC
Labels: 🐛 bug

**Comment by elchininet** [comment] 2024-01-05 19:47
@basilfx,

[A new version has been released](https://github.com/NemesisRE/kiosk-mode/releases/tag/v5.2.0). Please, test it and report back.

Regards

**Comment by basilfx** [comment] 2024-01-06 08:52
@elchininet Thank you, I can confirm that it works.

**Comment by elchininet** [comment] 2024-01-06 09:47
Super, good to know 👍🏼
