### ISSUE TITLE
BREAKING: HA 2023.5.0.dev20230402 - Uncaught TypeError: Cannot read properties of null (reading 'querySelector') 

### ISSUE THREAD

**Issue by zibous** [NemesisRE/kiosk-mode#30] opened 2023-04-03 08:06 UTC
breaking all custom cards that use this functionality

```
Logger: frontend.js.latest.202304020.dev
Source: components/system_log/__init__.py:254
First occurred: 09:57:26 (2 occurrences)
Last logged: 10:00:14

http://hahome.local:8123/hacsfiles/kiosk-mode/kiosk-mode.js:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')    
```

![Bildschirmfoto 2023-04-03 um 09 59 02](https://user-images.githubusercontent.com/30198737/229449131-2523014d-4e0f-485f-8861-ebf7814e6811.png)

**Comment by elchininet** [comment] 2023-04-03 18:38
Hi @zibous,
The management of `app-drawer` is being discussed in [this issue](https://github.com/NemesisRE/kiosk-mode/issues/27). I‘ll let this issue open because it is referring to Home Assistant `2023.5` but nothing should be developed until this version is at least in beta.
Regards.

**Comment by elchininet** [comment] 2023-04-05 18:32
Hi @scooper1,
@NemesisRE will take care of the release when he is back. For now you can follow [these instructions](https://github.com/NemesisRE/kiosk-mode/issues/27#issuecomment-1492947745) and here you can find [a compiled version of the library](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) if you don‘t know or can‘t compile the code.
Regards

**Comment by scooper1** [comment] 2023-04-05 19:10
on the second try got it to work by renaming both directory and file then updating the resource file to new names

**Comment by samuolis** [comment] 2023-04-05 20:14
I'm still getting those type errors with 2023.4 version:
```
http://homeassistant.local:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5206 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
http://homeassistant.local:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128178:1:5302 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
```

How this can be solved?

**Comment by elchininet** [comment] 2023-04-05 20:18
Hi @samuolis,
Please, refer to this issue: https://github.com/NemesisRE/kiosk-mode/issues/27#issue-1647324294
Regards

**Comment by Murianwind** [comment] 2023-04-07 01:42
I've updated to version 1.8.1, cleared the cache, and rebooted, but I'm still getting the error below.

Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 09:22:39 (4 occurrences)
Last logged: 10:38:18

https://******/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:13:44 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
https://*****/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:57:96 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')

Home Assistant 2023.4.1
Supervisor 2023.04.0
Operating System 9.5
Frontend 버전: 20230406.1 - latest

**Comment by elchininet** [comment] 2023-04-07 08:32
Hi @Murianwind,
This issue is for Home Assistant 2023.5, I‘ll tag you in the proper issue and we can discuss it there.
Regards

**Comment by RickeyWard** [comment] 2023-04-08 14:28
After upgrading to 1.8.1 my header and sidebar are correctly hidden, but background images no longer fill the viewport (they do if the kiosk-mode is not set with ?kiosk) seems to be the minimum height is not applying correctly to the view. In Home assistant 2023.4.1. The issue is that background images no longer fill the screen.

**Comment by elchininet** [comment] 2023-04-08 14:52
Hi @RickeyWard,
Please, refer to [this issue](https://github.com/NemesisRE/kiosk-mode/issues/43). It should be fixed in the next release.
Regards

**Comment by elchininet** [comment] 2023-04-29 07:11
Hi @zibous,
I have tested the library in `2023.5.0b2` and it works without any issues. Could you check on your side if you are able to reproduce the error above there?
Regards

**Comment by rjenx** [comment] 2023-04-29 11:02
> 

I am seeing this issue in 2023.4.6 

```
Logger: frontend.js.latest.202303091
Source: components/system_log/__init__.py:257
First occurred: 28 April 2023 at 08:17:16 (1 occurrences)
Last logged: 28 April 2023 at 08:17:16

http://192.168.1.70:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:13121 TypeError: null is not an object (evaluating 'this.drawerLayout.querySelector')
```

**Comment by elchininet** [comment] 2023-04-29 22:39
Please @rjenx,
This issue is about `2023.5.0` now in beta. Refer to my response to this issue when it was opened, Home Assistant `2023.6.0.dev20230429` is in development at the moment, nothing will be developed until this version is at least in beta.
Regards

**Comment by elchininet** [comment] 2023-05-01 03:53
Sorry @rjenx,
I am noticing that you were referring to `2023.4.6` not to `2023.6`. Please, if your issue continue, open a new issue and we can continue from there.
Regards

**Closed** 2023-05-02 15:27 UTC
