### ISSUE TITLE
Doesn't load on a fresh tab, but works when refreshing

### ISSUE THREAD

**Issue by DevoliaEsp** [NemesisRE/kiosk-mode#63] opened 2023-04-21 12:39 UTC
Hi,

Since the last update, kiosk mod only partially works, on firefox
When launching HA on a new tab 95% of the time, kiosk mod won't load, with the associated error showing up in the console : 

Uncaught (in promise) TypeError: this.ha.hass.resources is null
    t https://mydomain/hacsfiles/kiosk-mode/kiosk-mode.js:1
    <anonymous> https://mydomain/hacsfiles/kiosk-mode/kiosk-mode.js:1

When I F5, most of the time kiosk mode then starts to function, but each new tab doesn't load kiosk mode on it's first try.

I'm using : 
- Kiosk Mode version 1.8.3 
- Firefox 112.0.1 
- HA 2023.3.5

I've tried on Edge, and the problem doesn't appear there.
Also I've clean my cache, without success.

Thanks for the plugin, when it was working it was doing wonders

**Comment by elchininet** [comment] 2023-04-22 00:01
Hi @DevoliaEsp,

Are you sure you are having that since the last update?

[The last update](https://github.com/NemesisRE/kiosk-mode/releases/tag/v1.8.3) was mostly configuration changes but in terms of code changes it was only one line and not related to `this.ha.hass.resources`. That part of the code was shipped [in version 1.8.1](https://github.com/NemesisRE/kiosk-mode/releases/tag/1.8.1).

I‘ll try to reproduce your issue in Firefox. When you say "when launching HA on a new tab" is just open Home Assiastant  for the first time, right?

Regards

**Comment by DevoliaEsp** [comment] 2023-04-22 10:02
Oh indeed, I went straight from 1.7.8 to 1.8.3 my bad.
I've checked, and yes, the problem starts to appear in 1.8.1, but isn't present in 1.7.8

To detail on the issue a bit more : When opening HA for the first time, there's a 50/50% chance that kiosk mode will function
Then, once I refresh the page, it will mostly resolve, even if sometimes, when refreshing an instance where kiosk mode was functionnal, it won't function again.

Thanks for your help

**Comment by elchininet** [comment] 2023-04-22 11:15
Hi @DevoliaEsp,
Perfect, that helps me a lot and confims what is exactly the version in which you are having issues. I‘ll try to reproduce it, and we can start from there.
Regards

**Comment by elchininet** [comment] 2023-04-22 16:13
Hi @DevoliaEsp,
I was able to reproduce your issue in Firefox browser. This issue will be solved when [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/60) gets merged and a new version is released.

**Closed** 2023-04-22 21:30 UTC

**Comment by elchininet** [comment] 2023-05-08 16:07
Hi @DevoliaEsp,
A new version of the library has been released. It contains the fix to your issue.
Regards
