### ISSUE TITLE
[BUG] Dashboard in kiosk mode in read only mode

### ISSUE THREAD

**Issue by mizarmess** [NemesisRE/kiosk-mode#275] opened 2024-09-20 23:32 UTC
**Describe the bug**
When setting up kiosk mode on a dashboard and using on Android 13 (I'm personally using Samsung S20 FE) you cannot click on any button. It seems is in some kind of read only mode.

**To Reproduce**
1. Add code to dashboard:

kiosk_mode:
  mobile_settings:
    kiosk: true
    hide_header: true
    hide_sidebar: true
    hide_menu_button: true
    hide_overflow: true

2. Run the HA Companion App and navigate to the dashboard
3. Dashboard in read only mode

**Expected behavior**
You should be able to click on buttons and use the dashboard as in normal mode

**Versions:**
 - Home Assistant: 2024.9.2
 - Kiosk-Mode: v6.1.1

**Comment by elchininet** [comment] 2024-09-21 00:13
Hi @mizarmess,
I cannot reproduce your issue, I am able to click on my dashboard using your configuration, so I suspect that your issue is coming from somwhere else.
Please, set [Chrome Remote Debugging](https://developer.chrome.com/docs/devtools/remote-debugging) in your Android device and check what is blocking your dashboard and also check for errors in the browser console.
Regards

**Comment by elchininet** [comment] 2024-09-21 00:35
Hi @mizarmess,

I was able to reproduce the issue in a new dashboard (for some reason it is not reproducible in my already created dashboards). Just using this configuration:

```yaml
kiosk_mode:
  kiosk: true
```

Let the debugging part on my side. I'll check what is happening there.

**Comment by elchininet** [comment] 2024-09-21 01:34
@mizarmess,
I don't know since when this has been ocurring but basically, there are new elements, classes and animations in the elements related to the sidebar that makes everything break.

I was not able to detect it because it only occurs when one navigates through the sidebar to a dashboard with `hide_sidebar` (or `kiosk`) activated, so one needs to have the sidebar activated in one dashboard and deactivated in other. It doesn't occur either if the panel that is loaded has the sidebar hidden.

In the moment that a navigation to a dashboard without sidebar occurs, the animation that closes the sidebar doesn't finish and then multiple classes and attributes are not removed.

I'll work on a fix for this and I'll let you know when it is solved.

Regards

**Comment by mizarmess** [comment] 2024-09-21 10:17
Thnx for the prompt looking into the issue and I'm glad you at managed to reproduce it and have some ideas where the problem is. Looking forward for the fix. 

Regards :)

**Comment by elchininet** [comment] 2024-09-21 11:20
Hi @mizarmess,
When [this pull request](https://github.com/NemesisRE/kiosk-mode/pull/276) gets merged and a new version of the addon is released, your issue will be solved.

This issue was introduced by [this change](https://github.com/home-assistant/frontend/pull/16033), basically, the body scroll is removed and the interaction with the screen is removed until the sidebar closes (and hiding the sidebar impedes that the logic to remove all those blockers run).

Regards

**Comment by NemesisRE** [comment] 2024-09-21 16:44
I am currently on vacation without connection to my dev environment, will be back on wednesday to release a new version sorry for the delay 🥺

**Closed** 2024-09-21 16:45 UTC
Labels: 🐛 bug

**Comment by elchininet** [comment] 2026-06-03 21:32
Hi @mizarmess,
In Home Assistant `2026.6.0` `kiosk-mode` got broken so [it needed to be adapted](https://github.com/elchininet/custom-sidebar/pull/656). Your use case is not tested in the end-to-end tests because it is something hard to reproduce. When a new version of `kiosk-mode` is released and you update to Home Assistant `2026.6.0`, it would be good if you test it and report back.
