### ISSUE TITLE
hide Assistant does not hide the icon

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#16] opened 2023-03-14 22:12 UTC
thx for adding the hide search and hide assistant options.

I can hide the search icon using
```
# Hides the search icon
  - entity:
      input_boolean.hide_search: 'on'
    hide_search: true
```

and the same for the account, which is kind of neat indeed

However, using
```
# Hides the assistant icon
  - entity:
      input_boolean.hide_assistant: 'on'
    hide_assistant: true
```

does Not hide the assistant icon unfortunately.

Ive added all booleans in a card, to easily control settings:

<img width="478" alt="Scherm­afbeelding 2023-03-14 om 23 09 20" src="https://user-images.githubusercontent.com/33354141/225153597-c156df63-f390-4d8c-b7d0-1ce6e64a64d3.png">

**Comment by elchininet** [comment] 2023-03-16 10:43
Hi @Mariusthvdb,

The `hide_assistant` option what does is to hide the second `ha-icon-button` inside `app-toolbar`, this is not perfect because if Home Assistant front-end code changes this needs to be changed too but it is better than the previous behaviour (all the buttons getting hide if the `hide_search` is `true`).

Please, could you share what is the HTML structure of your header? Just to see which is the second `ha-icon-button` for you. On my side this is what I get using the `hide_assistant` option:

![image](https://user-images.githubusercontent.com/3728220/225592735-c2a9ca5b-21e8-48fb-a920-65a807aa9f06.png)

**Comment by Mariusthvdb** [comment] 2023-03-16 11:21
seeing this in Chrome. What browser are you using?

<img width="928" alt="Scherm­afbeelding 2023-03-16 om 12 20 32" src="https://user-images.githubusercontent.com/33354141/225601805-99f554e6-3beb-44a4-a5f9-460fc06fdd65.png">

**Comment by elchininet** [comment] 2023-03-16 11:33
For the screenshot I used Firefox, but regularly I test the code with Opera, Safari, Firefox and Chrome. This is the same result in Chrome:

![image](https://user-images.githubusercontent.com/3728220/225603677-41c3cbe1-831f-4f92-b6c7-4db6a47bbac1.png)

At least we know that your second button is indeed the Assistant one. So, let‘s debug this further. Could you try to apply the option without the entity config?, I mean, directly in the configuration to see if it doesn‘t occur there. Trying to isolate the issue. Also, try to clean the local storage to see if this is not related to some cache issue.

**Comment by Mariusthvdb** [comment] 2023-03-16 11:41
Ive set it fixed in the kiosk_mode config for now and yes, that makes a difference....


<img width="220" alt="Scherm­afbeelding 2023-03-16 om 12 39 43" src="https://user-images.githubusercontent.com/33354141/225605927-43c5cd70-5327-4ac5-9962-a5b49ed77dba.png">

now can that be? did I make a mistake in the boolean config? let me double check:

this is my full config:
```
hide_assistant: true

non_admin_settings:
  hide_menubutton: true
  hide_overflow: true
  ignore_entity_settings: true

mobile_settings:
  hide_menubutton: true
  hide_overflow: true
#   ignore_entity_settings: true

entity_settings:
#Hides both the header and sidebar.
  - entity:
      binary_sensor.kiosk_mode: 'on'
#      input_select.mode: Kiosk
    kiosk: true
# Hides only the header
  - entity:
      input_boolean.hide_header: 'on'
    hide_header: true
# Hides only the sidebar. Disables swipe to open.
  - entity:
      input_boolean.hide_sidebar: 'on'
    hide_sidebar: true
# Hides only the sidebar menu icon. Does not disable swipe to open.
  - entity:
      input_boolean.hide_menubutton: 'on'
    hide_menubutton: true
# Hides the top right menu
  - entity:
      input_boolean.hide_overflow: 'on'
    hide_overflow: true
# Hides the account icon
  - entity:
      input_boolean.hide_account: 'on'
    hide_account: true
# Hides the search icon
  - entity:
      input_boolean.hide_search: 'on'
    hide_search: true
# # Hides the assistant icon
#   - entity:
#       input_boolean.hide_assistant: 'on'
#     hide_assistant: true
```

and this is the boolean:

<img width="582" alt="Scherm­afbeelding 2023-03-16 om 12 41 18" src="https://user-images.githubusercontent.com/33354141/225606329-78a05e18-c6d8-4692-b873-09d026abf299.png">

**Comment by elchininet** [comment] 2023-03-16 11:47
That‘s good to know. We have isolated the issue :)
Do not worry, let me test with the entities option to see if I can reproduce it and if I find the issue I‘ll push a pull request. I‘ll let you know.
Regards

**Comment by Mariusthvdb** [comment] 2023-03-16 11:49
the fact I dont see the nth child in the path is rather odd though, and might explain why my earlier card_mod codes both icons, and not just the single.

**Comment by elchininet** [comment] 2023-03-16 17:56
Hi @Mariusthvdb,
JFYI, I have found the issue. I is a small typo (that‘s why I would like to use `TypeScript` in the project).
I will fix it directly [in the pull request that I am preparing](https://github.com/NemesisRE/kiosk-mode/pull/17).
I‘ll let you know.

**Comment by elchininet** [comment] 2023-03-17 09:43
@Mariusthvdb,
The pull request has been merged, once it gets released this issue will be solved. 👍

**Closed by elchininet** 2023-03-17 09:43 UTC

**Comment by Mariusthvdb** [comment] 2023-03-17 09:49
yes, it's live, and I can confirm it to work.
thanks!

**Comment by elchininet** [comment] 2023-03-17 10:18
Glad to hear that it is working.
About what you are mentioning, I think that is pretty much related to [this one that you already created](https://github.com/NemesisRE/kiosk-mode/issues/14).

**Comment by Mariusthvdb** [comment] 2023-03-17 10:20
I would not see why? This has nothing to do with the menu items as such? Snd is purely a header button thing.

Sure, the buttons for assistant and search move to the menu, but that should not cause the 3-dots to disappear?

**Comment by elchininet** [comment] 2023-03-17 10:23
I was referring to the movement of the icons to the menu that you have noticed before, I didn‘t read the text after the image. That should not happen because the selectors for the icons and the menu are different, most probably the HTML structure changes is smaller screens. I need to check what is happening there. Feel free to open a new issue.
