### ISSUE TITLE
lovelace view issue crop when updated v1.8.1

### ISSUE THREAD

**Issue by liamlain** [NemesisRE/kiosk-mode#43] opened 2023-04-07 04:34 UTC
cleared browser cache still the same.Tested using ?disable_km will become normal.

1st image when enable kiosk mode the bottom is cropped 
![01](https://user-images.githubusercontent.com/93088569/230541281-29957835-7b1b-46fc-a875-e456b5e38d1a.jpg)

2nd image showing after disable kiosk mode it showing normal
![02](https://user-images.githubusercontent.com/93088569/230541356-14de77bd-5707-46f5-b4b8-ef1fcd865a13.jpg)

**Comment by gzzyyt** [comment] 2023-04-07 04:57
Same question as you

The specific situation is reflected in the link below


[https://github.com/NemesisRE/kiosk-mode/issues/27](url)

**Comment by elchininet** [comment] 2023-04-07 07:32
Hi @liamlain,
That background is not coming from Home Assistant, could you explain a bit how you added it or which theme are you using?
Regards

**Comment by liamlain** [comment] 2023-04-07 08:25
> Hi @liamlain, That background is not coming from Home Assistant, could you explain a bit how you added it or which theme are you using? Regards

The background image is from default using iOS Themes - Dark Mode and Light Mode

**Comment by DerEmder** [comment] 2023-04-07 08:36
The same here. Another issue is that kiosk_mode is removing the header bar on views where it is not even activated in the yaml. In other words - ALL my dashboard in all views have now kiosk_mode enabled but I only use it in one view.

I also use iOS theme dark but my other self-made theme generates the same problem.

The (left) sidebar is still not removed.

![Bildschirmfoto vom 2023-04-07 10-29-53](https://user-images.githubusercontent.com/91392202/230574464-fda0807c-e92b-4460-916a-d4c43fc9fce2.jpg)

**Comment by elchininet** [comment] 2023-04-07 08:39
>Another issue is that kiosk_mode is removing the header bar on views where it is not even activated in the yaml. In other words - ALL my dashboard in all views have now kiosk_mode enabled but I only use it in one view.

Hi @DerEmder,
Please, open an issue for that and let‘s try to debug it there.
Regards

**Comment by elchininet** [comment] 2023-04-07 08:41
>The background image is from default using iOS Themes - Dark Mode and Light Mode

@liamlain, perfect, I‘ll check what is happening there.

**Comment by Mariusthvdb** [comment] 2023-04-07 08:42
please be aware of https://github.com/home-assistant/frontend/releases/tag/20230406.1

HA Frontend had some background issues

**Comment by elchininet** [comment] 2023-04-07 08:56
Hi @liamlain,
When [this](https://github.com/NemesisRE/kiosk-mode/pull/44) gets merged and released this issue should be solved.
Regards

**Comment by elchininet** [comment] 2023-04-07 08:57
> please be aware of https://github.com/home-assistant/frontend/releases/tag/20230406.1
> 
> HA Frontend had some background issues might be related?
> 
> new Frontend is released in HA 2023.4.1

I think that it is unrelated, I was able to reproduce the issue in `HA 2023.4.1` using the theme provided by @liamlain.

**Comment by Mariusthvdb** [comment] 2023-04-07 08:59
ok, that's fine. just figured Id mention it.
Cant reproduce here btw, but that is of no consequence as long as you can ;-)

**Closed** 2023-04-07 19:33 UTC

**Comment by pergolafabio** [comment] 2023-04-08 11:04
i have indeed same issue, but i also see PR is merged, it will be probably for 1.8.2 then? Do we need to enter anything to define 100% height?

**Comment by elchininet** [comment] 2023-04-08 11:49
Hi @pergolafabio,
It is already merged but no new version has been released. Once @NemesisRE releases a new version it should be solved.
Regards

**Comment by elchininet** [comment] 2023-04-09 13:04
Hi @liamlain,
[A new version](https://github.com/NemesisRE/kiosk-mode/releases/tag/1.8.2) has been released. Please, test it and let me know if the issue is resolved.
Regards

**Comment by liamlain** [comment] 2023-04-10 04:24
tested new version,the new update is fixed the problem.thanks !!

**Comment by AlexKusnezov** [comment] 2023-04-13 08:22
hey, I'm still getting this with v1.8.3:
```Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 10:02:26 (1 occurrences)
Last logged: 10:02:26

http://192.168.2.109:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128181:1:19567 TypeError: null is not an object (evaluating 'this.overlayMenu.dataset')
```

**Comment by elchininet** [comment] 2023-04-13 21:12
Hi @AlexKusnezov,
Are you still having the issue mentioned at the beginning of this thread or are you just receiving that JavaScript error in the logs?
