### ISSUE TITLE
[BUG] Gap at the top after 2024.11.0

### ISSUE THREAD

**Issue by rosicenko** [NemesisRE/kiosk-mode#295] opened 2024-11-08 16:47 UTC
**Describe the bug**
After update to new version of HA 2024.11.0 there is empty gap instead of the header. So entire dashboard is also moved below this gap/invisible header.

**To Reproduce**
kiosk_mode:
  mobile_settings:
    hide_header: true
    ignore_entity_settings: true
    custom_width: 480
    custom_height: 480
    hide_dialog_header_action_items: true
    hide_dialog_history: true
    hide_dialog_attributes: true

**Expected behavior**
In previous version there was no gap and dashboards looked fine

**Screenshots**
![image](https://github.com/user-attachments/assets/bb573a2f-4f1e-4703-988d-51f8fd52133d)
![kiosk mode_gap](https://github.com/user-attachments/assets/55ed6f03-3e1b-4a01-aab8-1eef1987fe53)

**Versions:**
 - Home Assistant: [e.g. 2024.11.0]
 - Kiosk-Mode [e.g. v6.3.1]

**Additional context**

**Comment by NemesisRE** [comment] 2024-11-08 16:59
I can not reproduce that behavior

**Comment by apfffr** [comment] 2024-11-08 17:04
I have the exact same issue

Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0
Kiosk Mode v6.3.1

Kiosk config:
`kiosk_mode:
  entity_settings:
    - entity:
        input_boolean.system_kiosk: 'on'
      kiosk: true
    - entity:
        input_boolean.system_kiosk: 'off'
      kiosk: false`

It looks like the header bar just becomes black instead of completely disappearing

**Comment by elchininet** [comment] 2024-11-08 17:04
>I can not reproduce that behavior

Me neither, this is using the Docker demo:

| 2024.9.1 | 2024.11.0 |
| -------- | --------- |
| ![image](https://github.com/user-attachments/assets/cf9373a6-6985-4104-b45e-965953ccd93f) | ![image](https://github.com/user-attachments/assets/1f659443-20f6-49f2-81e4-9ea7371e1e5b) |

@rosicenko,
Please, could you give more information about your dashboard?
What kind of layout are you using?

**Comment by rosicenko** [comment] 2024-11-08 17:09
I just discovered the "right" combination for this behaviour. It is when kiosk mode is used together with theme called: Material Rounded No Mod
![image](https://github.com/user-attachments/assets/69c5795b-cce3-4a58-b03b-7d22e7536201)

**Comment by elchininet** [comment] 2024-11-08 17:11
>I just discovered the "right" combination for this behaviour. It is when kiosk mode is used together with theme called: Material Rounded No Mod

Could you provide a link to the repo of that theme?

**Comment by rosicenko** [comment] 2024-11-08 17:13
> > I just discovered the "right" combination for this behaviour. It is when kiosk mode is used together with theme called: Material Rounded No Mod
> 
> Could you provide a link to the repo of that theme?

Here it is:
https://github.com/Nerwyn/material-rounded-theme

Issue seems to be on the side of this theme. Kiosk mode is most probably ok.

**Comment by elchininet** [comment] 2024-11-08 17:17
>Here it is:
>https://github.com/Nerwyn/material-rounded-theme
>
>Issue seems to be on the side of this theme. Kiosk mode is most probably ok.

I'll check to see from which side is coming the style that adds the padding.

>Ah makes sense being the theme. I am using Metro Theme which has the same issue
>
>https://github.com/Madelena/Metrology-for-Hass

Thanks, I can debug better with more options

**Comment by elchininet** [comment] 2024-11-08 17:41
@rosicenko,

In the case of `material-rounded-theme`, the padding is being added [here](https://github.com/Nerwyn/material-rounded-theme/blob/0aad431216d0d46579a10aff28d256bf761c7774/src/common/view.css#L3). The padding is being added assuming that the header is occupying that space, if the header is not there, then the space is shown. You would need to open an issue in the repo to see if there is an alternative (the theme is done assuming that the regular Home Assistant elements will be there).

![image](https://github.com/user-attachments/assets/17d95f6f-7564-487c-bef9-e0f867168d9c)


@apfffr,

I installed the `Metrology-for-Hass` theme and tested with the Metro Green, Orange, Blue and Red, but it doesn't add any padding. Could you tell me which specific theme you are using?

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/aa9437d6-9026-4d4b-8383-c352efe61466">

**Comment by apfffr** [comment] 2024-11-08 17:54
In HACS it's called "Metrology - Metro + Fluent + Windows Themes - by mmak.es"
linking this repo: https://github.com/Madelena/Metrology-for-Hass
v.1.9.1

It seems it doesn't matter which exact theme I select. I am using Metro Purple, but Metro Blue is also affected. Also the Fluent Slate etc.

**Comment by apfffr** [comment] 2024-11-08 17:55
But my themes are dark maybe that does affect it? I don't know where to select that anymore...like system darkmode

**Comment by elchininet** [comment] 2024-11-08 18:21
@rosicenko,
Just FYI, I am able to reproduce the same using the Docker demo which is in `2024.9.1` at the moment (it is a fresh Home Assistant instance with just `kiosk-mode` installed). So I assume that if you are not having the same before `2024.11.0` some caching was avoiding that.

![image](https://github.com/user-attachments/assets/46162184-fc4f-42a2-904a-f2ceaf7df534)

**Comment by rosicenko** [comment] 2024-11-08 19:16
> @rosicenko, Just FYI, I am able to reproduce the same using the Docker demo which is in `2024.9.1` at the moment (it is a fresh Home Assistant instance with just `kiosk-mode` installed). So I assume that if you are not having the same before `2024.11.0` some caching was avoiding that.

A lot of interesting info. I will post all this at Material Rounded Theme repo. Thank you a lot 👍

**Comment by erkac** [comment] 2024-11-09 12:28
Hi, I've noticed the same issue after installing `2024.11.0` however on one device the gap is not present, so it seems that the issue is there for some time already. I'm using **noctis** theme: https://github.com/aFFekopp/noctis

**Comment by elchininet** [comment] 2024-11-09 13:00
> Hi, I've noticed the same issue after installing `2024.11.0` however on one device the gap is not present, so it seems that the issue is there for some time already. I'm using **noctis** theme: https://github.com/aFFekopp/noctis

Hi @erkac, let me check to tell you from which place the padding is coming in your case.

**Comment by elchininet** [comment] 2024-11-09 13:09
Hi @erkac,
I cannot reproduce it using `noctis` theme, there is no padding on top using the Docker demo (in `2024.9.1` or in `2024.11.0`). It seems that in your case (as well as in the case of @apfffr) it is coming from somewhere else.

Could you please take a screenshot of your browser dev tools with the element that has the padding?

![image](https://github.com/user-attachments/assets/f3f01821-5c11-4773-ad5d-4f36f7d7aeb8)

**Comment by erkac** [comment] 2024-11-09 20:01
It seems it is caused by `hui-view-container` `padding-top` as shown on the screenshots...
![CleanShot 2024-11-09 at 20 58 07@2x](https://github.com/user-attachments/assets/45bc30d3-9468-4a48-bc37-cdee5dc4f33e)
![CleanShot 2024-11-09 at 20 57 58@2x](https://github.com/user-attachments/assets/722d8d67-bcd6-4639-8bd6-7c155bc94909)

**Comment by elchininet** [comment] 2024-11-09 20:24
>@elchininet It seems it is caused by hui-view-container padding-top as shown on the screenshots...

That `padding-top` is the regular one of Home Assistant that should be `0px` when `kiosk-mode` hides the header because it also sets `--header-height` in `0px` and `calc(var(--header-height) + env(safe-area-inset-top))` should return `0px`.

![image](https://github.com/user-attachments/assets/b9b05f4e-d3e4-4797-b51d-cec1ab01efb5)

In your screenshot you are filtering the styles searching by `hui`. Do not filter the styles and check if the `--header-height` variable is set in `0px`. Something interesting in your screenshot are the bunch of styles that you have in that element, which I don't have, so I suspect that in your case something is adding them.

**Comment by erkac** [comment] 2024-11-10 20:26
@elchininet in my case `--header-height` is `48px`

![CleanShot 2024-11-10 at 21 02 41@2x](https://github.com/user-attachments/assets/73f08faf-9a17-4f98-827d-cd1e2c09e9ac)

it seems it it set in `themes/noctis/noctis.yaml`:
![CleanShot 2024-11-10 at 21 24 39@2x](https://github.com/user-attachments/assets/976bdbae-7ad2-418c-9278-beacf45a2fe7)

however when I changed it to `0px` there is no gap, on top but the whole page is somehow corrupted, here is example from my iPhone:
![IMG_5E44FA59E812-1](https://github.com/user-attachments/assets/8db2f463-30ca-4f41-a43a-8ee2779f9b6d)

**Comment by elchininet** [comment] 2024-11-10 21:12
>@elchininet in my case --header-height is 48px

`48px` is the default value that Home Assistant adds but it gets overridden by `kiosk-mode`. In your case it seems that something is overriding `kiosk-mode`.

Check from which place is the `48px` coming, in your screenshot you are filtering the styles by `header-he` so I cannot see from which place it is coming but as it says `element.style,` most probably it is coming from the bunch of styles that you have in that element that I noticed before. We need to check if those styles are added by `noctis` or by something else.

But it is weird that you notice this just in the new Home Assistant release, if `noctis` is adding those styles, that should occur in any Home Assistant version

**Comment by pskowronek** [comment] 2024-11-10 21:53
Not sure if this will add anything to this discussion, but might help.

Today after updating HA to the newest version I observed the same behavior. Briefly going through this discussion, I've checked whether my theme is to blame so I disabled it, and it fixed the problem - my theme is `Fluent Blue` originating from HACS theme: https://github.com/Madelena/Metrology-for-Hass

Dashboard fragment:
```
[cut]
views:
  - title: Overall
    path: default_view
    icon: mdi:speedometer-slow
    type: custom:layout-card
    layout_type: custom:horizontal-layout
    layout:
      width: 150
      max_cols: 4
    theme: Fluent Blue # <---- 
[cut]
```

**Comment by elchininet** [comment] 2024-11-10 22:21
Hi @pskowronek,

Everything is valid to discover from which place is coming your issue. I tested the Metrology theme before and I could not detect any issue ([here](https://github.com/NemesisRE/kiosk-mode/issues/295#issuecomment-2465470616)). But that was using the Home Assistant Masonry layout. 

In your screenshot I am seeing that you are using `custom:horizontal-layout`, is it from [layout-card](https://github.com/thomasloven/lovelace-layout-card)? I need to reproduce it to see from which place is coming. Maybe this is a combination of multiple things at the same time?

**Comment by pskowronek** [comment] 2024-11-10 22:27
> Hi @pskowronek,
> In your screenshot I am seeing that you are using `custom:horizontal-layout`, is it from [layout-card](https://github.com/thomasloven/lovelace-layout-card)? I need to reproduce it to see from which place is coming. Maybe this is a combination of multiple things at the same time?

Most probably yes :) I have it installed, it's been awhile when I set it up :)
I will try to turn off this layout, gimme a sec.

**Comment by pskowronek** [comment] 2024-11-10 22:30
The problem still appears with this configuration:
```
[cut]
views:
  - title: Overall
    path: default_view
    icon: mdi:speedometer-slow
#    type: custom:layout-card
#    layout_type: custom:horizontal-layout
#    layout:
#      width: 200
#      max_cols: 4
    theme: Fluent Blue
    badges: []
    cards:
      - type: vertical-stack
[cut]
```

**Comment by elchininet** [comment] 2024-11-10 22:30
>I will try to turn off this layout, gimme a sec.

No need :)

I was able t reproduce it using the theme directly in the view as you. I need to check from which place it is coming.

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/7fff528a-3ca2-4f72-bc84-0e78c8640865">

**Comment by elchininet** [comment] 2024-11-10 22:34
So in summary. If I select the theme in my profile it doesn't happen (that was what I was doing before):

<img width="1413" alt="image" src="https://github.com/user-attachments/assets/930e13d1-d7f0-438d-ba18-4dcb664dc96e">

If I set the theme directly in the view it happens:

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/0b3f63c4-83bf-401f-bf19-9f187cc3bd75">

I need to check what is the difference between the both.

**Comment by pskowronek** [comment] 2024-11-10 22:56
!important? :)

**Comment by elchininet** [comment] 2024-11-10 23:07
What happened in previous Home Assistant versions was that the bunch of styles where applied to the `hui-view` element (inside the `#view` element) and now there are no two separated elements as before, there is a single element called `hui-view-container` with all those styles which overrides the `kiosk-mode` variable.

This is what happened before:

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/bd02daad-52cd-483c-8240-8a450e44ffe4">

So, @apfffr, @erkac, @NathanVanCleave and @pskowronek, if you confirm that you are using the theme applied directly to a view, then this is not coming from your themes as the @rosicenko issue, this is coming from Home Assistant and this should be arranged in `kiosk-mode` side.

>!important? :)

In this case it is a variable not a declaration. I need to check how can we deal with Home Assistant in this case.

**Comment by elchininet** [comment] 2024-11-10 23:43
[A fix](https://github.com/NemesisRE/kiosk-mode/pull/301) is coming for the issue applying a theme to a view. I need to confirm if all the reports in this thread were applying a theme to a view instead of applying the theme globally, so in that case this fix should fix the issue that all of you are having.

**Comment by pskowronek** [comment] 2024-11-11 00:29
> [A fix](https://github.com/NemesisRE/kiosk-mode/pull/301) is coming for the issue applying a theme to a view. I need to confirm if all the reports in this thread were applying a theme to a view instead of applying the theme globally, so in that case this fix should fix the issue that all of you are having.

mine was in `view`, I confirm.

**Comment by elchininet** [comment] 2024-11-11 00:34
>mine was in view, I confirm.

Yes, I know. Thanks to your report I was able to reproduce it adding a theme directly to a view (and you were not sure if it would add anything to the discussion 😉)

**Comment by NathanVanCleave** [comment] 2024-11-11 02:15
Mine was also being applied to a view, not globally.

**Comment by erkac** [comment] 2024-11-11 07:02
Yes, I can also confirm that removing `theme: noctis` from the view fixed the issue.

**Comment by elchininet** [comment] 2024-11-11 10:16
A new version has been released. Please, test it and report back.

**Comment by pskowronek** [comment] 2024-11-11 10:35
> A new version has been released. Please, test it and report back.

for me it works properly now. Thanks @elchininet for such a quick response!

**Comment by elchininet** [comment] 2024-11-11 16:01
>Offtopic, but how did you get the secondary line showing number of 'devices' in the sidebar? Is this a mod, or a pre-release of HA?

It has been done with [custom-sidebar](https://github.com/elchininet/custom-sidebar) and [a JavaScript template](https://github.com/elchininet/custom-sidebar?tab=readme-ov-file#javascript-templates) in the `info` option of those items retrieving the devices and filtering them to get the proper number.

**Comment by apfffr** [comment] 2024-11-11 16:38
> A new version has been released. Please, test it and report back.

It does work now, thanks a lot for the quick fix

**Comment by elchininet** [comment] 2024-11-11 18:36
It seems that the issue is fixed, closing this issue.

**Closed** 2024-11-11 18:36 UTC
Labels: 🐛 bug
