### ISSUE TITLE
[ERROR] TypeError: Cannot read properties of undefined (reading 'hass') #189

### ISSUE THREAD

**Issue by Drealine** [NemesisRE/kiosk-mode#197] opened 2024-02-04 19:21 UTC
Hi
i've the same problem than this issue closed : https://github.com/NemesisRE/kiosk-mode/issues/189

`kiosk-mode.js?hacstag=497319128520:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hass')
    at t.<anonymous> (kiosk-mode.js?hacstag=497319128520:1:43922)
    at kiosk-mode.js?hacstag=497319128520:1:1499
    at Object.next (kiosk-mode.js?hacstag=497319128520:1:1604)
    at kiosk-mode.js?hacstag=497319128520:1:520
    at new Promise (<anonymous>)
    at e (kiosk-mode.js?hacstag=497319128520:1:265)
    at t.entityWatchCallback (kiosk-mode.js?hacstag=497319128520:1:43790)
    at Object.callback (kiosk-mode.js?hacstag=497319128520:1:43661)
    at connection.js:23:34
    at Array.forEach (<anonymous>)`

I don't known why is it but It block call_event action in developpment mode. 
Thank you!!

**Comment by elchininet** [comment] 2024-02-04 19:53
Hi @Drealine,

As the issue that you linked, I need to ask the same because without that information there is not nothing to do:

>Following the stack trace, it originated from an entity change. Could you share your config and what are those entities that you are watching for changes?

Regards

**Comment by elchininet** [comment] 2024-02-04 21:42
Hi @Drealine,
I am inspecting the `JavaScript` code to see where are those errors located. Together with the config it will be important that you share how did you install `kiosk-mode`.
Regards

**Comment by Drealine** [comment] 2024-02-05 12:46
Yeah but how can I found what entity change create this issue ? I've got a lot of entity update in my dashboard.

**Comment by Drealine** [comment] 2024-02-05 12:49
Hi
I've installed Kiosk with HACS and put kiosk_mode in yaml on the adaptive dashboard provided by UI Minimalist.

**Comment by elchininet** [comment] 2024-02-05 12:50
@Drealine,

I mean, share here your config to check if you are using any [entity_settings](https://github.com/NemesisRE/kiosk-mode#entity_settings). If you are not using `entity_settings` at all is something good to know too.

Regards

**Comment by Drealine** [comment] 2024-02-05 19:10
Hi @elchininet 
I'm not using entity_settings, I've just set yaml to hide header with a specific user (my wallmount pannel).
If I go to settings, yes I see a lot of error. But if I close setting tab and just keep a tab with my dashboard in my browser, I don't have errors.

**Comment by elchininet** [comment] 2024-02-05 22:19
>I'm not using entity_settings, I've just set yaml to hide header with a specific user (my wallmount pannel).

Good to know, then it is not related to `entity_settings`.

>If I go to settings, yes I see a lot of error. But if I close setting tab and just keep a tab with my dashboard in my browser, I don't have errors.

Yes, but this was not what I was asking for. I need that you go to the config panel, refresh the browser being in that panel, open the console and check if the `kiosk-mode` `console.info` is there.

<img width="216" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/f9c19c55-e9b9-4b73-a04e-0c1d42aa0b3b">

**Comment by Drealine** [comment] 2024-02-07 07:03
Hi @elchininet 
Yes is here : 
![image](https://github.com/NemesisRE/kiosk-mode/assets/61891683/59e2c8e9-168a-4339-86cc-ec5e952c112d)
Thank you!

**Comment by elchininet** [comment] 2024-02-07 09:51
Then that is the issue, that should not be there.

You mentioned before that you installed the plugin through HACS, but what HACS does is to add the resource as a lovelace resource (they can be seen in `config/lovelace/resources`). Those resources are only loaded in lovelace dashboards, but as your code is executed in other dashboards (e.g. the config dashboard) I suspect that you have installed the plugin in another way (maybe as an [extra_module_url](https://www.home-assistant.io/integrations/frontend/#extra_module_url)).

So, let‘s try to debug why is the plugin being executed in non-lovelace dashboards. Inspect the code and check how many scrpips are loading the `kiosk-mode.js` file and try to inderify how are those resources loaded in your config. At least we detected where the issue is, it should be easy t solve it.

Regards

**Comment by elchininet** [comment] 2024-02-09 17:49
Hey @Drealine,
Did you have time to debug the issue and discover how is the plugin code loaded?

**Comment by Drealine** [comment] 2024-02-11 13:43
> You mentioned before that you installed the plugin through HACS, but what HACS does is to add the resource as a lovelace resource (they can be seen in `config/lovelace/resources`). Those resources are only loaded in lovelace dashboards, but as your code is executed in other dashboards (e.g. the config dashboard) I suspect that you have installed the plugin in another way (maybe as an [extra_module_url](https://www.home-assistant.io/integrations/frontend/#extra_module_url)).

No, I confirm that I've installed directly on HACS plugin. And I can see that is adding in resources : 
![image](https://github.com/NemesisRE/kiosk-mode/assets/61891683/cc5966ce-a5da-4452-98d7-bfbce2a87369)



> So, let‘s try to debug why is the plugin being executed in non-lovelace dashboards. Inspect the code and check how many scrpits are loading the `kiosk-mode.js` file and try to indentify how are those resources loaded in your config. At least we detected where the issue is, it should be easy to solve it.

For that, I'm not expert about this. I just looking into console mode and I can see that some HACS plugin are loaded. 
Please let me know how can I debug it.
Thank you!

**Comment by elchininet** [comment] 2024-02-11 14:56
That's really weird. Resources installed through HACS should not be loaded in other dashboards but Lovelace ones. That is the reason for the error, it is trying to access the lovelace panel (in which `kiosk-mode` stores the configuration, but it doesn't exist in non-lovelace dashboards)

Please, uninstall `kiosk-mode` completely, restart, check that you don't see `kiosk-mode` in your console at all. Install `kiosk-mode` again and check if you get the same if you refresh the config dashboard (or any other non-lovelace dashboard like Map, Energy, Media, etc).

Regards

**Comment by Drealine** [comment] 2024-02-11 17:04
Same problem. With uninstall, it's ok.
But after install with HACS, do the same thing.

**Comment by elchininet** [comment] 2024-02-11 17:56
Hi @Drealine,
What custom integrations and plugins have you installed apart from `kiosk-mode`?
Do you have `browser-mode` installed?
Regards

**Comment by Drealine** [comment] 2024-02-11 19:08
> Hi @Drealine, What custom integrations and plugins have you installed apart from `kiosk-mode`? Do you have `browser-mode` installed? Regards

Yep. Browser mod installed and actived for all users.

**Comment by elchininet** [comment] 2024-02-11 21:16
>Yep. Browser mod installed and actived for all users.

Hi @Drealine,
I regret that we didn‘t started from  there 😅

I didn‘t think of that, but it is logic now, that‘s one of the Browser-Mod features: load all the resources in all dashboards (because in that way you can use any custom card in any popup regardless if you are in a Lovelace dashboard or not).

I‘ll try to make a check to just avoid executing `kiosk-mode` if the dashboard is not a Lovelace one for those that have this plugin installed using Browser-Mod. I‘ll this issue open until then.

Regards

**Comment by elchininet** [comment] 2024-02-12 12:27
Hi @Drealine,
It would be great if you can test [this gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2). It tries to solve your issue but I need you to confirm that it indeed solves it. You need to uninstall `kiosk-mode` fro HACS, verify that it is not loaded after a restart and then [install it manually](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#installation).
If you confirm that it solves your issue, I‘ll submit a pull request with the changes.
Regards

**Comment by Drealine** [comment] 2024-02-12 19:29
Hi @elchininet 
Ok, so it's ok. I continue to have kiosk-mode loaded outside lovelace but I don't have errors now.
Thank you!!

**Comment by elchininet** [comment] 2024-02-12 19:36
Super @Drealine, I‘ll submit the PR.

And yes, the plugin will continue being loaded in non-lovelace dashboards, that is done by Browser-Mod and cannot be avoided, the change is to avoid it executing if that happens.

Once the PR is merged and a new version is released, you can uninstall the manual version and install the new version through HACS instead.

**Comment by elchininet** [comment] 2024-02-12 19:41
Hi @Drealine,
When [this](https://github.com/NemesisRE/kiosk-mode/pull/200) gets merged and a new version is released, you can uninstall the manual version and install the latest version in HACS.
Regards

**Comment by Drealine** [comment] 2024-02-12 19:45
> Hi @Drealine, When [this](https://github.com/NemesisRE/kiosk-mode/pull/200) gets merged and a new version is released, you can uninstall the manual version and install the latest version in HACS. Regards

thank's again for your fast and hard work :)

**Closed** 2024-02-13 07:12 UTC
Labels: 🐛 bug
