### ISSUE TITLE
[BUG] After update to v5.0.0 unable to hide header.

### ISSUE THREAD

**Issue by Joshbloam** [NemesisRE/kiosk-mode#153] opened 2023-12-11 17:26 UTC
Unable to hide header using non_admin_settings.

title: Overview
kiosk_mode:
  non_admin_settings:
    hide_header: true

Header still shows on dashboard for users accounts on my ipad. This worked and header was hidden prior to updating. 

![image](https://github.com/NemesisRE/kiosk-mode/assets/10256258/d4f7e023-fa5a-46d3-a51a-2532841c3689)

**Versions:**
 - Kiosk-Mode v5.0.0
 - Core 2023.12.1
 - Supervisor 2023.11.6
 - Operating System 11.2
 - Frontend 20231208.2

**Additional context**

**Comment by elchininet** [comment] 2023-12-11 18:41
Hi @Joshbloam,

Check in your browser console if you have the `kiosk-mode` console info.

<img width="226" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/9209d204-d3f6-41ed-9d2b-b34b79b16b06">

Also check for any error in the console related to `kiosk-mode`.

I have tried on my side and the `non_admin_settings` is working propely. Version `5.0.0` only fixed a bug related to more-info dialogs options, so the issue that you are having should not be related to `non_admin_settings` config.

Regards

**Comment by Joshbloam** [comment] 2023-12-11 19:39
Hi Iván,

Thanks for the information. Forgive me I am only about 2 months new to HA.
How do I check the kiosk-mode console info?

Thanks,
Josh

**Comment by Joshbloam** [comment] 2023-12-11 19:51
ahh It's definitely something with my ipad/HA ios app. The header is being properly hidden on web when I logon to a user account.

**Comment by elchininet** [comment] 2023-12-11 19:53
>Thanks for the information. Forgive me I am only about 2 months new to HA.

Do not worry.

>How do I check the kiosk-mode console info?

Just open your Home Assistant instance in your computer browser logged as a non-admin user. If you use Chrome or Firefox, right click on the screen and select `inspect`, then go to `console`. If you use Safari, go to `settings > advanced` and check `Show features for web developers`, the you can do the same to open the `console`.

**Comment by elchininet** [comment] 2023-12-11 19:55
>ahh It's definitely something with my ipad/HA ios app. The header is being properly hidden on web when I logon to a user account.

Mmm, this will be harder to debug.

In Home Assistant, could you go to `Settings > System > Logs` and check if there is any error related to `kiosk-mode`?

**Comment by Joshbloam** [comment] 2023-12-12 04:37
Not seeing any errors related to kiosk-mode. I will have to look deeper on this. I did update HA to 2023.12.1 I wonder if that had anything to do with it. I may restore back just to test.

**Comment by elchininet** [comment] 2023-12-12 08:14
Hi @Joshbloam,

Do not rollback Home Assistant, that should not be the issue (we have several end-to-end tests in place and they are running at the moment in 2023.12.1).

We need to make sure that kiosk mode is executed on your tablet. So, backup your configuration first and let's do this.

First of all, how many Lovelace dashboards do you have? Do you have the configuration in all of them? Do you show the default Lovelace dashboard in your tablet?

After backing up your config, add a minimal configuration without any non-admin settings, hiding just the notifications for example, and check if it is applied on your tablet.

**Comment by Joshbloam** [comment] 2023-12-12 15:20
Just one. I set up a test dashboard and did a minimum config like you said.
Hiding just the notifications and then the assist button. Both work on web
and both fail on tablet. Looking at all logs I have available and see no
errors related to kiosk.

I run HA as a virtual machine so restoring to a previous state is just a
click. After reverting back to core 2023.12.0 everything on the tablet is
working as expected. It seems the jump from Core 2023.12.0 to 12.1 broke it
for me and I just didn't catch it right away.

Josh

**Comment by elchininet** [comment] 2023-12-12 20:25
That is really weird, there is no difference between `2023.12.0` and `2023.12.1` in terms of layout. I think that the issue should be related to some kind of caching system of your tablet. Do you use the Home Assistant iOS app or Safari in your iPad?

**Comment by Joshbloam** [comment] 2023-12-13 00:09
I have to fall on my sword. I apologize for causing confusion and for
speaking too soon. After testing more, the HA version does not matter.
kiosk mode stops executing on my tablet at version v5.0.0.

[image: image.png]

Uninstalling then reinstalling kiosk mode, selecting v4.6.0 from hacs,
works. I repurposed a gen one ipad air as my dashboard (as opposed to
throwing it in the trash) and it's on an older ios version (12.5.7). I'm
not sure it's worth your time to fix, especially if the issue is not
experienced on newer IOS devices. More than willing to help you try and
debug it.

Also want to clarify the issue is only experienced on the following:
Ipad air 1 ios version 12.5.7
HA ios app
kiosk-mode v5.0.0

Josh

**Comment by Joshbloam** [comment] 2023-12-13 00:11
![image](https://github.com/NemesisRE/kiosk-mode/assets/10256258/7e8acf3d-3a99-4e2e-9c2e-52d372553244)

**Comment by elchininet** [comment] 2023-12-13 00:46
>After testing more, the HA version does not matter.
>kiosk mode stops executing on my tablet at version v5.0.0.

This makes more sense :)

I would like to know what is happening there, and if it works with version `v4.6.0` it would be good to detect what is failing in  `v5.0.0`.

Could you try to open Home Assistant in your Safari browser and check if the issue also happens there?

Regards

**Comment by elchininet** [comment] 2023-12-13 18:30
Hi @Joshbloam,

Taking the information that you gave me about your device being in iOS `12.5.7` I started to research what could be unsuported in your device from the new code. I think that I have found it, thr new code uses [private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) and Safari iOS supports them [from the version 14.5](https://caniuse.com/mdn-javascript_classes_private_class_fields).

Even if that is a very old device, I think that it is very common that one takes an unused old device to give it a second life as a kiosk device. For that reason I‘ll try to make the code compatible with Ecma Script 5, for that I need to make some fixes in the library that we are using to query for elements and later I‘ll do the proper changes here.

I‘ll need you to test that the fix works in your device so open this issue open until then.

Regards

**Comment by elchininet** [comment] 2023-12-13 21:11
Hi @Joshbloam,
To make sure that your issue is related to what I was mentioning, could you try to [install manually](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#installation) this [gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2)? As you have the iOS app, you would need [to clear completely the cache](https://github.com/NemesisRE/kiosk-mode/issues/112#issuecomment-1739876659) after the manual install.
Let me know if that version runs without issues in your device.
Regards

**Comment by Joshbloam** [comment] 2023-12-14 00:38
> 
> Could you try to open Home Assistant in your Safari browser and check if the issue also happens there?
> 
Everything works when I load the dashboard in Safari. I refuse to do any web browsing on it because it's ridiculously slow lol.

> Hi @Joshbloam,
> 
> Taking the information that you gave me about your device being in iOS `12.5.7` I started to research what could be unsuported in your device from the new code. I think that I have found it, the new code uses [private properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties) and Safari iOS supports them [from the version 14.5](https://caniuse.com/mdn-javascript_classes_private_class_fields).
> 
> Even if that is a very old device, I think that it is very common that one takes an unused old device to give it a second life as a kiosk device. For that reason I‘ll try to make the code compatible with Ecma Script 5, for that I need to make some fixes in the library that we are using to query for elements and later I‘ll do the proper changes here.
> 
> I‘ll need you to test that the fix works in your device so open this issue open until then.
> 
> Regards

This is awesome you were able to identify this so quickly. It's really is useless for 99% of everything at this point but makes a great dashboard for the coffee table :)



> Hi @Joshbloam, To make sure that your issue is related to what I was mentioning, could you try to [install manually](https://github.com/NemesisRE/kiosk-mode?tab=readme-ov-file#installation) this [gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2)? As you have the iOS app, you would need [to clear completely the cache](https://github.com/NemesisRE/kiosk-mode/issues/112#issuecomment-1739876659) after the manual install. Let me know if that version runs without issues in your device. Regards

Thanks for the documentation here. I have the custom kiosk-mode.js under my www folder. 
![image](https://github.com/NemesisRE/kiosk-mode/assets/10256258/c0e57797-4d44-44ce-bb1a-4f9ed5cc5418)

Not 100% on how to install this. How do I tell if my confi is YAML, non-YAML, or Storage Mode? How do I point it to the new version? Here is what my dashboard resources look like:
![image](https://github.com/NemesisRE/kiosk-mode/assets/10256258/ccb0e70d-7e43-4c8b-8264-59b67d3e76d4)

Browser Inspect >Console still shows me at version 4.6.0.

Thanks,
Josh

**Comment by elchininet** [comment] 2023-12-14 09:58
>Everything works when I load the dashboard in Safari. I refuse to do any web browsing on it because it's ridiculously slow lol.

Do you mean with version `5.0.0`? If that is the case that is very weird, it means that the issue is in Home Assistant and not in this plugin which seems to not be the case.

>This is awesome you were able to identify this so quickly. It's really is useless for 99% of everything at this point but makes a great dashboard for the coffee table :)

👍

>Not 100% on how to install this. How do I tell if my confi is YAML, non-YAML, or Storage Mode? How do I point it to the new version? Here is what my dashboard resources look like:

First of all, completely uninstall the plugin through HACS, after that, place the gist code inside the `www` folder:

```bash
www/kiosk-mode.js
```

Then go to the dashboard resources (you should not have any `kiosk-mode` resource then yet), create a new resource and insert this:

```
/local/kiosk-mode.js?v5.0.1
```

Clean cache and test it.

**Comment by Joshbloam** [comment] 2023-12-15 02:05
> Do you mean with version `5.0.0`? If that is the case that is very weird, it means that the issue is in Home Assistant and not in this plugin which seems to not be the case.

Nope. 4.6.0.

Followed the steps to remove from HACS and install. Cleared front end cache. Everything works!! Tablet is happy 😊

![image](https://github.com/NemesisRE/kiosk-mode/assets/10256258/7126d69d-a886-4404-b342-770482de403c)

**Comment by elchininet** [comment] 2023-12-15 08:02
@Joshbloam,

That's great, that means that indeed that was the issue.

I'll open the pull request, once it is merged and a new version is released, you can remove the manual install and install it again through HACS.

Regards

**Comment by Joshbloam** [comment] 2023-12-15 17:45
Thank you!

**Closed** 2023-12-16 13:51 UTC
Labels: 🐛 bug
