### ISSUE TITLE
Lovelace config not found (during startup)

### ISSUE THREAD

**Issue by Mariusthvdb** [NemesisRE/kiosk-mode#75] opened 2023-05-25 06:34 UTC
might have been there before, but only noticing now, because I had Inspector open during startup:

<img width="1145" alt="Scherm­afbeelding 2023-05-25 om 08 32 26" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/73999bfe-05f0-486a-9394-c3ab9aab3314">

Not sure if this has to do anything with my use of !includes, or yaml way of splitting the config, but it would be nice if we could prevent this from happening.

HA 2023.5.4
Kiosk Mode 1.9.0

**Comment by elchininet** [comment] 2023-05-25 10:50
Hi @Mariusthvdb, please check manually if your config is available in that element, if not, we need to find where it went maybe due to your set up. 

Just for context, the code checks multiple times for the config and after several unsuccessful intents, it throws that warning and it continues with the default configuration.

Regards

**Comment by Mariusthvdb** [comment] 2023-05-25 11:16
to be honest, I dont know what you are looking for...

i have a ui-lovelace.yaml in my /config root, and that has no refererence to kiosk mode.

next, my config is like this:
```
lovelace:
  mode: yaml
  resources: !include /config/dashboard/resources.yaml
  dashboards:

    ui-overzicht:
      mode: yaml
      filename: dashboard/dashboards/ui-overzicht.yaml
      title: Overzicht
      icon: mdi:home

    ui-familie:
      mode: yaml
      filename: dashboard/dashboards/ui-familie.yaml
      title: Familie
      icon: mdi:home-account

#etcetc for all other dashboards
```

and all dashboards contain a reference to kiosk-mode like this:

```

title: Ha Main #Rpi4

button_card_templates: !include_dir_merge_named ../button_card_templates
decluttering_templates: !include_dir_named ../decluttering_templates
kiosk_mode: !include ../kiosk-mode/kiosk-mode.yaml

#swipe_nav:
#  wrap: false
#  animate: swipe
#  skip_tabs: 5,6,7,8
#  prevent_default: true
#  swipe_amount: 30

views:
  - !include ui-overzicht/view_overzicht_Welkom.yaml         #0
  - !include ui-overzicht/view_overzicht_Plattegrond.yaml    #1
  # etcetc
```

anything you can spot here, or something else you need to analyze this?

**Comment by elchininet** [comment] 2023-05-25 11:33
Hi @Mariusthvdb,
No worries then, I will ask you to look to some things with detailed explanation if I am not able to reproduce the issue following your same set up. For now, it will be helpful if you can tell me:
* Kiosk mode is not working for you because of this error?
* Is the error thrown in all the lovelace views or only in some of them?
* Is the error thrown in lovelace yaml mode views or also in normal ones?

Regards

**Comment by Mariusthvdb** [comment] 2023-05-25 11:38
- working properly all over!
- seems to be only logged during startup, I can not reproduce on a running system
- define 'normal' ;-)  if you mean UI configured?.... let me test:
    no, no logging while on a running system.

**Comment by elchininet** [comment] 2023-05-25 18:51
Oh, that is weird, I was not expecting that it worked.
Let me see if I can reproduce it, I‘ll let you know if I find it.
Regards

**Comment by elchininet** [comment] 2023-05-27 16:05
Hi @Mariusthvdb,
I was not able to reproduce it, even with a similar configuration. But I did some changes that could avoid such issue, please, could you test [the last code in the gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) and let me know if you receive any error?
Regards

**Comment by elchininet** [comment] 2023-06-01 09:03
@Mariusthvdb,
When [this one](https://github.com/NemesisRE/kiosk-mode/pull/80) gets merged and a new version is released, you can remove the gist hack and install the update.
Regards

**Closed** 2023-06-01 10:27 UTC
Labels: bug

**Comment by elchininet** [comment] 2023-06-01 10:41
Hi @Mariusthvdb,
A new version has been released. As I cannot reproduce it in my environment, could you update to that version and check that the issue is solved for you?
Regards

**Comment by Mariusthvdb** [comment] 2023-06-01 12:02
yes!!
it has been resolved. Magic, you are the best!

-----
1 tiny issue I had been wanting to mention for some time (and which was inherited from the original...):

<img width="184" alt="Scherm­afbeelding 2023-06-01 om 14 00 33" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/a8ec6693-f138-44a3-854a-5201ddd4cbe9">

maybe check the formatting of that console info line please?

**Comment by Mariusthvdb** [comment] 2023-06-01 12:43
using Safari on Mac, and it has been like that since forever... its about the only resource though:

<img width="380" alt="Scherm­afbeelding 2023-06-01 om 14 42 02" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/887f00fa-d39d-4316-b843-110f65f201af">

Chrome shows its out of the ordinary formatting too though, using twice the height

<img width="318" alt="Scherm­afbeelding 2023-06-01 om 14 42 55" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/2ea0363a-cb84-4062-b81e-0cf25650ffd0">

**Comment by elchininet** [comment] 2023-06-01 12:46
I'll test on Safari and see if I can fix it.
The Chrome one is OK, the height and paddings were done on purpose, so no issues there.

**Comment by elchininet** [comment] 2023-06-01 15:40
@Mariusthvdb,
FYI: https://github.com/NemesisRE/kiosk-mode/pull/82
