### ISSUE TITLE
[FR] Hide elements in more-info

### ISSUE THREAD

**Issue by BoneheadFraggle** [NemesisRE/kiosk-mode#93] opened 2023-06-14 15:46 UTC
**Is your feature request related to a problem? Please describe.**
I like to share my dashboards with family and friends, and then I think it is important to be able to only show what I feel is relevant.
All features in Kiosk Mode today are great - I have a few suggestions for further developing:

**Describe the solution you'd like**
I would like the options to hide certain elements in the more-info dialogs. 
Preferably each one separately, but all at once would be fine,

1. Hide more-info header (completely, including the cog wheel and three dot menu)
2. Hide more-info attributes (completely, including drop-down)
3. Hide more-info logbook and Logbook text
4. Hide more-info history (both the text "History" and the "Show more" link)

**Describe alternatives you've considered**
Today I edit a theme to achieve this, but including it in Kiosk Mode instead would make sense. I know other users want to "lock down" and minimize info in their Home Assistants as well.

**Additional context**
Before (don't mind the theme):
![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/8e789c2e-0e7f-40a8-a54f-8332c7049d52)

After:
![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/2211b1ac-5e5f-4cb5-bc35-939782c498fc)

**Comment by elchininet** [comment] 2023-06-14 16:10
Hi @BoneheadFraggle,
I‘ll take a look at this when I have some time, just a question:
Why do you think that it would be useful to hide the icon to close the dialog from other users?
Regards

**Comment by BoneheadFraggle** [comment] 2023-06-14 21:06
Sorry, bad wording from my side.

What I meant was in my opinion, the header with the close X does not provide any value for a "viewer". On a computer, you can press Esc to close the popup, or click beside the dialog. On a mobile, you use the back gesture/button. So I think it just takes up space by showing the entity name again in larger font.

I have learned that there are a lot of users that prefer this minimalistic interface that you get when you hide most stuff.
Both from a design perspective, and often combined with my approach - only show the stuff you want them to see/access.

Thanks for considering!

**Comment by elchininet** [comment] 2023-06-14 21:49
Hi @BoneheadFraggle,

If it is not something that needs to be hidden to avoid non-authorized user access the functionality then it is out of the scope of kiosk-mode and it can be achieved by other means, this library is not intended to achieve minimalistic intarfaces or change the style of elements, the functionality must be focused only in kiosk devices and how to use Home Assistant in such environments.

As I mentioned, I‘ll take a look at this when I have some time, but if I see that the elements are not elements in which a non-authorized user could perform actions that change the configuration or get control of the system then it is out of the scope of this plugin.

Regards

**Comment by BoneheadFraggle** [comment] 2023-06-16 20:56
I get it, absolutely. 
History and Logbook are typical things I want to hide non-authorized users access / guests / kids, and might be considered in-scope. Guess can't change anything, but are allowed to see things I don't think they should. Like who de-activated the alarm and stuff like that.

Personally, I hide all attributes as well. I rather accept the hassle to create template sensors for the data I actually want to share.
Hiding the header is just a minimalist visual bonus.

Thanks for all your efforts and again, thanks for considering.

**Comment by elchininet** [comment] 2023-06-17 11:58
Hi @BoneheadFraggle,
I already checked the elements that appear on the more info dialogs and it is right, there are many things that could be hidden from unauthorized users which fall in the scope of `kiosk-mode`. Now I need to check how to implement it 🙂
I‘ll let this feature request open until it is implemented. I‘ll let you know.
Regards

**Comment by elchininet** [comment] 2023-06-18 14:58
Hi @BoneheadFraggle,

A working in progress branch has been created to bring these features, it is just an starting point because I know that when it is implemented users will find more elements that would require to be hidden inside different kinds of info-dialogs, but these are just the most common ones.

To read more about the new options you can check [the next draft](https://github.com/NemesisRE/kiosk-mode/pull/94).

This would require testings before shipping this functionality. I have tested it just in my environment it would be good to check that it doesn‘t create issues in others. So please, uninstall the HACS version and [install manually](https://github.com/NemesisRE/kiosk-mode#installation) the version contained in [this gist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2), check if everything works OK for you and let me know.

@Mariusthvdb, jut for your information, if you think that you would use these options, it would be great if you can test them too.

Regards

**Comment by Mariusthvdb** [comment] 2023-06-18 15:18
I sure will, as I have long standing card-mod hacks to try to do that and most of them have become obsolete.

Tbh, I couldn't keep up with the frontend changes that kept being pushed.

That would be something to take into account. 

Unless these more-info mods use a great deal of common code with kiosk mode, it might be worth considering to create a separate custom tool for more-info's...

**Comment by elchininet** [comment] 2023-06-18 16:21
Hey @Mariusthvdb,
I have taken that into account. In theory, if something fails in the modal infos it should not break the rest of the àkiosk-mode` functionality. It should display some warnings just for logging purposes and for other elements it cannot even do that because not all the elements are always inside the modals, so the library should not try to select them and throwing errors if it cannot, as it does with the core elements.

**Comment by Mariusthvdb** [comment] 2023-06-19 15:07
yes they are loaded by HA< as I have made them I the UI, as is, (I purposely didnt change any naming yet, to be sure I get the correct entity_id's first)

ofc the mai connection to my setup and the Kiosk-mode versions would be:
```
  - entity:
      input_boolean.hide_dialog_header_history
    hide_dialog_header_history: true
  - entity:
      input_boolean.hide_dialog_header_settings
    hide_dialog_header_settings: true
  - entity:
      input_boolean.hide_dialog_header_overflow
    hide_dialog_header_overflow: true

  - entity:
      input_boolean.hide_dialog_history
    hide_dialog_history: true
  - entity:
      input_boolean.hide_dialog_history_show_more
    hide_dialog_history_show_more: true

  - entity:
      input_boolean.hide_dialog_logbook
    hide_dialog_logbook: true
  - entity:
      input_boolean.hide_dialog_logbook_show_more
    hide_dialog_logbook_show_more: true

  - entity:
      input_boolean.hide_dialog_attributes
    hide_dialog_attributes: true

  - entity:
      input_boolean.hide_dialog_media_actions
    hide_dialog_media_actions: true
  - entity:
      input_boolean.hide_dialog_update_actions
    hide_dialog_update_actions: true
  - entity:
      input_boolean.hide_dialog_climate_actions
    hide_dialog_climate_actions: true
```

as I took that from the preliminary documentation, and need to assure its correct...

just let me know what screenshots you need, happy to assist! as always

**Comment by elchininet** [comment] 2023-06-19 15:09
I‘ll take a look at it later. Basically I‘ll reproduce your config in a fresh instance to see if I can spot it.
Regards

**Comment by Mariusthvdb** [comment] 2023-06-19 15:34
sure, please let us know your findings, so we can again re-install and test.

**Comment by elchininet** [comment] 2023-06-19 16:24
Hi @Mariusthvdb,
I cannot reproduce it. I can push the changes to the docker demo, could you chackout the branch and run the demo and check if the configuration is similar o yours?

![image](https://github.com/NemesisRE/kiosk-mode/assets/3728220/31642fe0-466b-4e28-9aa9-8198bc3135c3)

**Comment by elchininet** [comment] 2023-06-19 16:25
By the way, I found a case that it is not covered. When the header icons are used and one returns to the previous window, anything that was hidden before it is shown again. I need to fix that.

**Comment by elchininet** [comment] 2023-06-19 16:27
This commit contains the configuration, check if the configuration is similar to yours:

https://github.com/NemesisRE/kiosk-mode/pull/94/commits/9bc3e0ad256e07e335a9d23afd24aca238850b6a

**Comment by Mariusthvdb** [comment] 2023-06-19 19:03
I missed the : 'on' after each input_boolean.... so now we are getting closer.

still this is really surprising:
<img width="496" alt="Scherm­afbeelding 2023-06-19 om 21 00 58" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/903479da-f971-4c59-a7be-689ea1b8fdbe">

and now observe the individual booleans:

<img width="577" alt="Scherm­afbeelding 2023-06-19 om 21 01 09" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/0da7e972-53e3-4d38-8a50-6828004dae40">

I fear the group functionality does not work because of this (so please if you can, make sure Kiosk-mode does that natively)

**Comment by elchininet** [comment] 2023-06-19 20:25
Hey @Mariusthvdb,
I didn‘t detect the `:`, yes, it seems that was the issue.
About your issue that it only works when it is opened first time but it doesn‘t work when it is already opened, it is something that I detected [here](https://github.com/NemesisRE/kiosk-mode/issues/93#issuecomment-1597460497), I need to fix it.
Regards

**Comment by elchininet** [comment] 2023-06-19 22:11
@Mariusthvdb,
The code in [the guist](https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2) has been updated and the new option has been added to [the draft](https://github.com/NemesisRE/kiosk-mode/pull/94). Check it on your side and let me know.
Regards

**Comment by Mariusthvdb** [comment] 2023-06-20 18:15
Sure will have a go at it.
Notice the new option is called ``` hide_dialog_action_items ``` 

That seems a bit backend-ish if you ask me. Why not simply ``` hide_dialog_header ``` since that is what it does?

**Comment by elchininet** [comment] 2023-06-20 18:49
@Mariusthvdb,
The header includes the close button, the title and the actions. That option hides only the actions, not the header. It is the same that would occur if the already implemented `hide_header` instead of hiding the header hides the actions (search, assistant, overflow_menu) ;)

**Comment by Mariusthvdb** [comment] 2023-06-20 18:58
cool, and talking about that:

<img width="394" alt="Scherm­afbeelding 2023-06-20 om 20 55 02" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/00b69fc7-9d56-4697-84d4-f03952123273">

adding that hide_dialog_header to the above options would be a nice addition! imagine changing

<img width="619" alt="Scherm­afbeelding 2023-06-20 om 20 57 12" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/78a79847-7ff8-4d02-9d23-15c9e85da631">

to this:

<img width="608" alt="Scherm­afbeelding 2023-06-20 om 20 57 19" src="https://github.com/NemesisRE/kiosk-mode/assets/33354141/62ed133b-2ee2-41f1-8b65-0a928402bef3">

with a simple click on that boolean option?

**Comment by elchininet** [comment] 2023-06-20 19:05
[That has been already discussed](https://github.com/NemesisRE/kiosk-mode/issues/93#issuecomment-1592035542) with @BoneheadFraggle. Thas‘s out of the scope of `kiosk-mode`. If the purpose is not to hide elements in which a non-authorized user could change things or access sensitive information, it should be achieved by other means.

**Comment by elchininet** [comment] 2023-06-20 19:07
By the way @BoneheadFraggle, this is your request, it would be good if you test it and check if everything works on your side.

**Comment by Mariusthvdb** [comment] 2023-06-20 19:09
sorry I missed that, I am tempted to no agree 100% with that statement, but, its your call ofc. It seems so very natural to add, and prevent a lot of 'sub' settings by adding it.

I just installed and tested, and can conform all actions to work now, also on the already selected booleans as tested earlier.
Great work!

**Comment by elchininet** [comment] 2023-06-20 19:22
>sorry I missed that, I am tempted to no agree 100% with that statement, but, its your call ofc. It seems so very natural to add, and prevent a lot of 'sub' settings by adding it.

It is OK to not agree, but there must be some limitations and some rules to keep the project in scope, if not, users will request whatever they think that would make the interface to look better or whatever they think that fits their needs, and that would make the project unmaintanable in a short time.

>I just installed and tested, and can confirm all actions to work now, also on the already selected booleans as tested earlier.
Great work!

Super, thanks for testing it. If you can let it run for a while it would be good, in that way if some error appear it could be fixed. I tried to make the refactoring in a way that if this functionality breaks, the core functionality of kiosk mode keeps running (because header and sidebar are the most important things of this library). But anyway it would be good to ensure ourselves that it is safe enough and it doesn‘t bring any issues.

**Comment by Mariusthvdb** [comment] 2023-06-21 07:19
sure, will do.

now we can create configs galore https://github.com/NemesisRE/kiosk-mode#conditional-lovelace-config and set specifics for admin/non-admin and per users. Nice!

**Comment by Mariusthvdb** [comment] 2023-06-21 07:29
separate post:
```
[ Non critial warning ] kiosk-mode: Cannot select ha-more-info-dialog::shadowRoot > ha-dialog after 500 attempts. Giving up!
```

schowing in inspector, dont no why yet.

**Comment by elchininet** [comment] 2023-06-21 11:20
>now we can create configs galore https://github.com/NemesisRE/kiosk-mode#conditional-lovelace-config and set specifics for admin/non-admin and per users. Nice!

Yes, this is something that has been implemented since a long time it seems. Take into account that for some kinds of users some elements are already hidden. For example, non-admins don‘t have the overflow menu and the settings in the header actions items in the more info modals, so those don‘t need to be configured for non-admins.

>is it strange to expect the toggles for the indivual actions to turn on, when turning on the input_boolean.hide_dialog_header_action_items ? And vice versa ?

This is how it works since the beginning, the library doesn‘t change the entitities states in home assistant, it just takes the information and apply the proper styles and some options take precedence over others (if an option overrides other options it doesn‘t matter the states of the laters, it just ignores their state). So, this is a summary (something that I have been thinking since a while to add to the documentation so this will serve as a base for that):

#### Options overriding tree

* `kiosk` overrides
    * `hide_header` overrides
        * `hide_search`
        * `hide_assistant` 
        * `hide_overflow` overrides
            * `hide_edit_dashboard`
            * `hide_refresh`
            * `hide_unused_entities`
            * `hide_reload_resources`
            * `block_overflow`
    * `hide_sidebar` overrides
        * `hide_account`
        * `hide_menubutton`
* `hide_dialog_header_action_items` overrides
    * `hide_dialog_header_history`
    * `hide_dialog_header_settings`
    * `hide_dialog_header_overflow`
* `hide_dialog_history` overrides
    * `hide_dialog_history_show_more`
* `hide_dialog_logbook` overrides
    * `hide_dialog_logbook_show_more` 
* `hide_dialog_attributes`
* `hide_dialog_media_actions`
* `hide_dialog_update_actions`
* `hide_dialog_climate_actions`
* `block_mouse`

#### Conditional options overriding tree

> Note: All these options override the previous ones in the root of `kiosk_mode`

* `entity_settings` overrides
    * `mobile_settings` overrides
        * `user_settings` overrides 
            * `admin_settings`
            * `non_admin_settings`

**Comment by elchininet** [comment] 2023-06-21 20:17
>[ Non critial warning ] kiosk-mode: Cannot select ha-more-info-dialog::shadowRoot > ha-dialog after 500 attempts. Giving up!

I placed the warnings just to be able to debug if something happens, when does this warning occurs? Do you have any issue with the more-info dialogs when it is triggered?

**Comment by elchininet** [comment] 2023-06-21 20:45
I have updated the gist, I detected a case in which that warning could be triggered and it should not in those cases. Try with the new version to see if the warning appears.

**Comment by BoneheadFraggle** [comment] 2023-06-25 21:11
I left for business for a few days and come back to this. I don't know what to say, sorry for not keeping up and awesome job guys! :-) 

I'll do my best to test it out in a few days and get back to you!

**Comment by BoneheadFraggle** [comment] 2023-06-25 22:16
Ok, I couldn't just let this sit.
I think I have tested all options now, and it just works. Really awesome!

I'd like to propose that 'hide_dialog_history_show_more' and 'hide_dialog_logbook_show_more' also hides the text "History" / "Logbook" (and the extra space) like the pictures in my example at the top. I don't think the text it add any value - you get it without pointing it out. 
But maybe that's just my personal minimalistic taste.

Thank you both, @elchininet for implementing this and @Mariusthvdb for showing me the path to hiding stuff to begin with quite some time ago. 

Great work.

**Comment by BoneheadFraggle** [comment] 2023-06-25 22:48
Maybe I found a bug/missing feature:
The attributes are not hidden from the `more-info-timer` even though `hide_dialog_attributes` is `true`.

I use this in my theme to hide it:
```
        more-info-timer:
          $: |
            ha-attributes {
              display: {{'none'}};
            }
```

**Comment by elchininet** [comment] 2023-06-26 11:27
>I think I have tested all options now, and it just works. Really awesome!

Glad to her that it is working on your end.

>I'd like to propose that 'hide_dialog_history_show_more' and 'hide_dialog_logbook_show_more' also hides the text "History" / "Logbook" (and the extra space) like the pictures in my example at the top. I don't think the text it add any value - you get it without pointing it out.

This is the same as hiding the title of the modal that we already discussed. The library should not be intended to hide what users consider adding value or not, but instead focusing in things that needs to be hidden to avoid cretain users/roles change configuration or see information that could be sensible because of the device (as a kiosk device) is being shown to a broader audience. The later is specific and very focused, the earlier is just too broad and depending on opinions. This kind of things should be achieved with generic tools open to do those kinds of changes as [card-mod](https://github.com/thomasloven/lovelace-card-mod).

>Maybe I found a bug/missing feature:
>The attributes are not hidden from the more-info-timer even though hide_dialog_attributes is true.

It is not implemented, the `ha-attributes` is only hidden inside the  `more-info-default`. Let me know how to access the more info timer dialogs to implement it, but [as I mentioned before](https://github.com/NemesisRE/kiosk-mode/issues/93#issuecomment-1596176535):

_I know that when it is implemented users will find more elements that would require to be hidden inside different kinds of info-dialogs_

So this is a good opportunity to indentify in which dialogs the `attributes` block is shown, if you can help with that it would be great.

Regards

**Comment by elchininet** [comment] 2023-06-26 22:26
Hi @BoneheadFraggle,
I cannot reproduce those dialogs because I don‘t have those entities. Could you take a screenshot of the developer tools with each one of those elements with the entire elements tree of their parents? Somethig like this:

<img width="801" alt="image" src="https://github.com/NemesisRE/kiosk-mode/assets/3728220/011a138f-8c72-4f52-b593-7f5eda166d3e">

**Comment by elchininet** [comment] 2023-06-26 22:34
@BoneheadFraggle,
I was able to reproduce the timer one, it was easy to set up. I would need a screnshot only of the vacuum one.

**Comment by elchininet** [comment] 2023-06-27 18:17
@BoneheadFraggle,

The code in the gist has been updated with the fix for hiding the attributes in `more-info-timer` and a new option `hide_dialog_timer_actions`. The only thing that is missing is the fix for `more-info-vacuum` attributes, when you send me a screenshot of the elements I can prepare the code to handle it.

Regards

**Comment by BoneheadFraggle** [comment] 2023-06-27 21:45
Great work!

Here is an example of the vacuum:

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/1992e051-a442-4d0b-a66a-368b548ab978)

Should `hide_dialog_timer_actions` hide the Start / Pause / Finish action buttons?
I doesn't for me (I can't see any difference). But the timer's attributes hides nicely with `hide_dialog_attributes`.

**Comment by Mariusthvdb** [comment] 2023-06-28 08:09
> 
> The code in the gist has been updated with the fix for hiding the attributes in `more-info-timer` and a new option `hide_dialog_timer_actions`. 

HI!
trying to stay up to date with the option, this is the only change being made so far (compared to the precious gist version)?:

https://gist.github.com/elchininet/9a2648ea0016d3194072712c745c5ad2#file-kiosk-mode-js-L124

**Comment by BoneheadFraggle** [comment] 2023-06-29 18:53
> It should hide this element, check the tree of your elements to see if it is the same.

Yep, it was probably a cache issue at my side. It works as intended now. Neat!

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/13bc3914-c910-4edd-be59-838d406741f3)

Versus

![image](https://github.com/NemesisRE/kiosk-mode/assets/2287810/ea2b3db1-4ad3-4a7d-9a53-01f4db71a756)

**Comment by elchininet** [comment] 2023-07-04 18:07
Hi @BoneheadFraggle,
The gist has been updated. Check if the `more-info-vacuum` attributes get hidden when the setting is set to `true`.
Regards

**Comment by BoneheadFraggle** [comment] 2023-07-05 08:21
> Hi @BoneheadFraggle, The gist has been updated. Check if the `more-info-vacuum` attributes get hidden when the setting is set to `true`. Regards

Yep, Vacuum also works now. Great work. Thanks!

A note: 
It seems like kiosk hides stuff in some other way then the themes I have used previously?
With the settings in kiosk-mode, I often need to refresh with CTRL+F5 or even restart HA to see the change, for example when I use entity settings with an input_boolean. I never needed that when using themes. I suppose that's a cache-thingy? 
So nothing wrong, just curious of the different behavior.

**Comment by BoneheadFraggle** [comment] 2023-07-06 06:54
I have only seen it when trying out the new features. After some more testing, I think it is related to when activating/changing settings. So if I setup kiosk with a lot of settings, restart HA and the client - then everything works smoothly.
But while trying out different kiosk settings, and changing the config back and forth, it seems like not all settings are applied (probably cached). Like if I hide attributes with an entity setting (an input_boolan). I then run F5 and CTRL+F5, the attributes are still showing even if I toggle the input_boolean. But after a HA restart, and browser restarts it works fine.

Again, not a problem really, maybe just related to my clients. I just haven't seen it before. 

Thank you very much for adding these features!

**Comment by Mariusthvdb** [comment] 2023-07-06 07:09
Can you pinpoint the specific settings that don't get applied?

All I see here is that any Boolean I toggle has immediate effect

**Comment by BoneheadFraggle** [comment] 2023-07-06 17:50
After more testing, I think the issue only occur when I use multiple browser windows. Typically one where I edit code, one for testing and one for reloading templates. Since I thought it was resolved but restarting HA, I guess the restart reset a session ID or something like that? So probably it had nothing to do with the restart, I would probably have had the same result by restarting all browsers.

So for now - no refresh issue.

**Comment by elchininet** [comment] 2023-07-07 10:15
@BoneheadFraggle,
I was trying to reproduce it having multiple sessions and editing the config and the templates on them but I could not reproduce it. I really don't know what could be happening on your side.

**Comment by elchininet** [comment] 2023-07-09 20:37
Hi @BoneheadFraggle and @Mariusthvdb,
It seems that this version has been tested already.
Just let me know if there are no objections and I‘ll enabled the pull request to be ready to be merged.
Regards

**Comment by BoneheadFraggle** [comment] 2023-07-09 22:10
No objections, seems to work perfectly fine.

Thanks!

**Closed** 2023-07-11 08:07 UTC
Labels: ✨ feature-request

**Comment by elchininet** [comment] 2023-11-11 14:37
Hi @BoneheadFraggle,
A  new section has been added to the [kiosk-mode complements documentation](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md#hide-the-header) showing how to hide the header in the more-info dialogs.
Regards

**Comment by BoneheadFraggle** [comment] 2023-11-11 18:51
> Hi @BoneheadFraggle, A new section has been added to the [kiosk-mode complements documentation](https://github.com/NemesisRE/kiosk-mode/blob/master/KIOSK-MODE-COMPLEMENTS.md#hide-the-header) showing how to hide the header in the more-info dialogs. Regards

Thanks! I do it in a similar way, with the addition of using an `input_boolean` for toggling, and a check which user it is.
So I always hide it from all other users but me - and I can toggle if I want to have access to overflow menus or not.

I think it is really kind to document it here so more people can find it. I know it is a popular thing to hide.

Great work!

**Comment by elchininet** [comment] 2023-11-11 22:15
@BoneheadFraggle,
If you hide more things through alternative methods, feel free to add them to the document.
Regards
